services:
  app:
    image: ghcr.io/wazam/r-fantasybaseball-indexer:latest
    container_name: anything-goes-archive
    ports:
      - "9009:9009"
    volumes:
      - ./data:/app/data
    environment:
      - REDDIT_CLIENT_ID= # REQUIRED, see README
      - REDDIT_CLIENT_SECRET= # REQUIRED, see README
      # - THREAD_TTL_HOURS=24
      # - SCHEDULER_INTERVAL_MINUTES=60
      # - BACKFILL_DATE= #YYYY-MM-DD
      # - TZ=UTC
      # - PUID=1000
      # - PGID=1000
    restart: unless-stopped
